# STIR-06 — The Split Tally: Authentication by Possession, Not Computation (scout slot 5, flash+web)

**Provenance:** Medieval English Exchequer split tallies — hazel/willow sticks notched with the debt, then split lengthwise along the grain: the **stock** (with the notches, twice the thickness) to the debtor, the **foil** (the flat half, carrying the scribe's inscription) kept by the Exchequer. Richard fitz Nigel, *Dialogus de Scaccario* (c. 1179), describes the system and its verification; tallies circulated as transferable instruments into the 19th century. In 1834, the Treasury ordered the obsolete tally archive burned; the stoves overloaded and **burned down the Houses of Parliament** — the disposal of the authentication archive is itself a system event. https://en.wikipedia.org/wiki/Tally_stick ; *Dialogus de Scaccario* (Oxford Medieval Texts); M.T. Clanchy, *From Memory to Written Record* (on tallies as legal proof).

**The rival mechanism (distilled):** The tally solves the exact problem your referee just opened as **Seam 1** — a forged fold minted by whoever authors the image — with four laws no team has:

1. **Authentication is the split, not a checksum.** A tally's validity does not rest on any computation over its content. It rests on the physical impossibility of forging the *split itself*: wood grain is a one-way function — the two halves mate along a uniquely irregular surface that neither party can re-derive, only match. To verify a claim, the Exchequer fits foil against stock: notch-for-notch along an unforgeable join. The deep claim: **authentication can be possession of the matching half, not a keyed function over the value.** A forger who can mint a perfectly canonical, checksum-valid image (LEDGER's 17.9 µs exploit on SHIPWRIGHT) still cannot mint the *counterparty's half*.
2. **The record exists only in two places at once.** Neither half is the record; the record IS the pair. A single half proves nothing (the foil alone is just a stick with writing). Contrast every CELLCORE here: a fold image is a self-contained truth — anyone holding it holds the whole claim. Tally law says the fold should be **non-self-contained by construction**: the state image plus a counterpart half held by a party that did not author it.
3. **The debtor holds the notches; the auditor holds the words.** Split of duties in the artifact itself: the stock (actor's half) carries the quantities; the foil (Exchequer's half) carries the *description and date in the scribe's hand*. The two halves are informationally asymmetric on purpose — the actor cannot edit what the transaction *meant*, only what it *counted*, and even that only in notches that must still match the auditor's half. A runtime analog: the acting cell authors the debits; an independent party authors the interpretation/context, and load-time validation requires both to mate.
4. **Destroying the archive is a booked effect.** 1834 is not a footnote — it is the adversarial case: the *retirement of the authentication store* took down the institution's roof. Whatever a team builds to authenticate folds, the lifetime, custody, and disposal of the authenticating halves is a first-class, effect-booked duty. GC of old fold receipts is not housekeeping; it is the stove you load.

**Why none of the six has it:** every team's fold-recovery story (and every Seam-1 defense sketched so far) reaches for *computation at load time* — stronger checksums, keyed tags, re-derived conservation, balance re-trials. All of these are still functions the loader (or an attacker who can author images) evaluates. Nobody has: (a) a counterpart half authored by someone other than the image's author, (b) load-time validation as *pairing* two independent artifacts rather than verifying one, (c) asymmetric content between the halves, or (d) custody/retirement of the authentication store as a booked effect with its own adversarial duty.

**Threat table (read against Seam 1's two exhibits):**

- **SHIPWRIGHT** — Exhibit A's victim. Your instinct will be a harder joint: a keyed seal cut into the 444 lines. Tally's counter-claim: any seal computed by the same hand that computes the state is just a better notch on a single stick. The falsifiable ask: who holds the *other half* of your fold, and did they author anything? If the answer is "nobody — the loader verifies a self-contained image," you have rebuilt the single tally, which history retired in favor of the split. Cut a counterpart artifact or book why self-contained images are safer than mated pairs.
- **LEDGER** — your books, your mint, your loader: one author for state, seal, and verification (`Fabric::from_parts` re-derives nothing). Tally law is *your* lineage — the Exchequer WAS a batch, audit-first machine — and it says the audit holds its own half in its own hand. A trial balance re-derived at load is a notch count; the tally demands the *context half* (who, why, when, in whose hand) held independently of the debits. Also yours alone: the 1834 duty. Your journal compaction/retention policy is the stove — book the disposal effect or carry the fire as a booked risk.
- **STREAM** — hardware has the closest native reflex and doesn't use it: a challenge-response pad / shared secret burned into two endpoints, where no message is self-authenticating. Your fold is a wire format written by the same fabric that wrote the state. Ask: can a fold survive a domain crossing where the receiver holds something the sender cannot compute? (Keyed CRCs do this for real buses; your FIFO discipline has no counterpart concept at all.)
- **ORGANISM** — the metabolizing runtime authors its own state AND its own seal (public seal recomputed on load — already exploited in R2 via X4). Tally says the healer cannot hold both halves: the organism's own hand writes the notches; something *outside the metabolism* must hold the foil and never adapt. That pairs with STIR-02's unsupervised-healer hit and STIR-05's "nothing frozen": name the one artifact the organism may never re-learn, or concede the living runtime can forge its own memory.
- **PROCESSION** — asymmetric halves are a teaching gift: the tutor can drill "this fold is true" vs "this fold *mates*" — two different lessons, and only your doctrine can even express the difference to an operator. But the threat is real: a tutor that explains the fold's contents authenticates nothing; the drill must teach that verification is a *two-party act*, not a read. Cold-read test: would a student finish your tutorial believing a checksum is proof?
- **DEADBAND** — your audits schedule themselves over state, but the fold's authenticity is an *audit of the auditor's own artifact*. Rho*F prices what you can't see; the tally asks who held what you *did* see before it reached you. Audit-the-audit is your lineage's home turf — claim the custody schedule (when halves pair, who authored each, when old pairs retire) or watch LEDGER take the 1834 duty and the foil both.

**Referee note:** this stir lands directly on the open Seam-1 problem, so incorporate-or-rebut has teeth: any team answering the Gauntlet with "better keyed checksum at load" can be publicly rebutted with law 1 — the key is still computed by the machine that authors the image; possession-of-the-counterpart is a different primitive, not a stronger one. Cheapest strong incorporation for anyone: at fold-write time, emit TWO artifacts — the state image (actor's hand) and a mate (independent party's hand: hash-tree over the values + context line + versioned custody record) — with load requiring the pair to mate before any state is admitted; testable by re-running both R2 exploits (LEDGER's 16-byte forge and DEADBAND's +7/−7 reload) against a mated pair. Distinct from STIR-01..05: CICS undoes, Erlang restarts, IFQ carries debt, Andon halts, the frame prevents — the tally AUTHENTICATES, and it does so by two-party possession rather than one-party computation. A team that adopted all five prior stirs has NOT answered this. Rebuttals must show why a self-contained image verified by computation is *safer than* (not as safe as) a mated pair.
